### ISSUE TITLE
gh-pages or wiki

### ISSUE THREAD

**Issue by alexandre-mbm** [cybermonde/odtphp#18]
Hint: content from [web.archive.org].

[web.archive.org]: https://web.archive.org/web/20120531095719/http://www.odtphp.com/index.php?i=home

**Comment by alexandre-mbm** [comment]
Wont do it?

**Comment by cybermonde** [comment]
Hello Alexandre,

The link is already included in https://github.com/cybermonde/odtphp/blob/master/README.md

Do not hesitate to give me more information about this issue.

Kind regards,
Laurent

**Comment by alexandre-mbm** [comment]
The web.archive's content can be lost easly.
